version: '3.8'

services:
  db:
    image: postgres:17
    container_name: nestjs-app-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: nestjs_dev
      POSTGRES_PASSWORD: nestjs_dev
      POSTGRES_DB: nestjs_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
